### ISSUE TITLE
ofp编译错误

### ISSUE THREAD

**Issue by alaleiwang** [lvsgate/lvs-dpdk#1]
严格按照文档上的步骤执行的，在as7.2环境下，ofp编译不过去
make[2]: Entering directory `/opt/work/ofp/example/ofp_vs'
  CC       ofp_vs-main.o
In file included from ./include/net/ip_vs.h:26:0,
                 from ./include/ofp_vs.h:27,
                 from main.c:15:
./include/linux/ip_vs.h:14:36: fatal error: libnl3/netlink/netlink.h: No such file or directory
 #include <libnl3/netlink/netlink.h>
                                    ^
compilation terminated.
make[2]: *** [ofp_vs-main.o] Error 1
make[2]: Leaving directory `/opt/work/ofp/example/ofp_vs'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/opt/work/ofp/example'
make: *** [all-recursive] Error 1

**Comment by lvsgate** [comment]
这个装了吗？
yum install libnl3 libnl3-cli

**Comment by lvsgate** [comment]
如果装了libnl3，看是不是转到/usr/local下面了，加到C_INCLUDE_PATH里去

**Comment by alaleiwang** [comment]
yum install libnl3 libnl3-cli
另外yum install libnl3-devel，安装包如下
rpm -qa|grep libnl      
libnl3-3.2.21-10.el7.x86_64
libnl3-cli-3.2.21-10.el7.x86_64
libnl-1.1.4-3.el7.x86_64
libnl3-devel-3.2.21-10.el7.x86_64

现在错误变成：
In file included from ./include/linux/ip_vs.h:14:0,
                 from ./include/net/ip_vs.h:26,
                 from ./include/ofp_vs.h:27,
                 from main.c:15:
/usr/include/libnl3/netlink/netlink.h:24:36: fatal error: netlink/netlink-compat.h: No such file or directory
 #include <netlink/netlink-compat.h>
                                    ^
compilation terminated.
make[2]: *** [ofp_vs-main.o] Error 1
make[2]: Leaving directory `/opt/work/ofp/example/ofp_vs'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/opt/work/ofp/example'
make: *** [all-recursive] Error 1

**Comment by alaleiwang** [comment]
libnl3-devel include文件默认是到/usr/include/libnl3
rpm -ql libnl3-devel-3.2.21-10.el7.x86_64|grep include
/usr/include/libnl3
/usr/include/libnl3/netlink
/usr/include/libnl3/netlink/addr.h
/usr/include/libnl3/netlink/attr.h
/usr/include/libnl3/netlink/cache-api.h
/usr/include/libnl3/netlink/cache.h
/usr/include/libnl3/netlink/cli
/usr/include/libnl3/netlink/cli/addr.h
/usr/include/libnl3/netlink/cli/class.h

**Comment by alaleiwang** [comment]
是因为libnl3版本低吗？

**Comment by alaleiwang** [comment]
rpm -ql libnl3-devel-3.2.28-3.el7_3.x86_64|grep  compa    
/usr/include/libnl3/netlink/netlink-compat.h

libnl3是有头文件netlink-compat.h的，
但错误提示引用的是netlink/netlink-compat.h，而不是libnl3/netlink/netlink-compat.h
/usr/include/libnl3/netlink/netlink.h:24:36: fatal error: netlink/netlink-compat.h: No such file or directory
#include <netlink/netlink-compat.h>

修改include path,出别的错
C_INCLUDE_PATH=/usr/include/libnl3/netlink/ make    
In file included from /opt/work/dpdk//x86_64-native-linuxapp-gcc/include/rte_memory.h:55:0,
                 from /opt/work/dpdk//x86_64-native-linuxapp-gcc/include/rte_malloc.h:45,
                 from ./include/ofp_vs.h:17,
                 from main.c:15:
/opt/work/dpdk//x86_64-native-linuxapp-gcc/include/rte_common.h: In function ‘rte_str_to_size’:
/opt/work/dpdk//x86_64-native-linuxapp-gcc/include/rte_common.h:361:2: error: ‘errno’ undeclared (first use in this function)
  errno = 0;
  ^
/opt/work/dpdk//x86_64-native-linuxapp-gcc/include/rte_common.h:361:2: note: each undeclared identifier is reported only once for each function it appears in
In file included from /opt/work/dpdk//x86_64-native-linuxapp-gcc/include/rte_mempool.h:76:0,
                 from ./include/ofp_vs.h:18,
                 from main.c:15:
/opt/work/dpdk//x86_64-native-linuxapp-gcc/include/rte_ring.h: In function ‘__rte_ring_mp_do_enqueue’:
/opt/work/dpdk//x86_64-native-linuxapp-gcc/include/rte_ring.h:464:13: error: ‘ENOBUFS’ undeclared (first use in this function)
     return -ENOBUFS;

**Comment by alaleiwang** [comment]
看了一下，是ofp/example/ofp_vs这部分的问题
执行的gcc是：
echo "  CC      " ofp_vs-ofp_vs_ctl.o;gcc -DHAVE_CONFIG_H -I.  -I/opt/work/ODP-DPDK//include -I/opt/work/ODP-DPDK/include   -I/opt/work/ODP-DPDK/include   -I. -I. -I../../include/api -I../../example/common  -pthread  -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wold-style-definition -Wpointer-arith -Wcast-align -Wnested-externs -Wcast-qual -Wformat-nonliteral -Wformat-security -Wundef -Wwrite-strings -DOFP_PLAT_ODP_DPDK -DOFP_CONFIG_DEFAULT -I../../include -I../../include/api -I/usr/local/include/libnl3 -I/opt/work/dpdk//x86_64-native-linuxapp-gcc/include -I./include -msse4.2 -Woverride-init -DCONFIG_IP_VS_PROTO_TCP -DCONFIG_IP_VS_PROTO_UDP -DCONFIG_IP_VS_PROTO_ICMP -DCONFIG_OFP_VS_RTE_TIMER -g -O2 -MT ofp_vs-ofp_vs_ctl.o -MD -MP -MF .deps/ofp_vs-ofp_vs_ctl.Tpo -c -o ofp_vs-ofp_vs_ctl.o `test -f 'ofp_vs_ctl.c' || echo './'`ofp_vs_ctl.c

其中-I/usr/local/include/libnl3这个路径指错了，调整这个就好了，或者使用C_INCLUDE_PATH

但该编译指令还是通不过
example/ofp_vs]# make 
  CC       ofp_vs-ofp_vs_ctl.o
ofp_vs_ctl.c: In function ‘__ip_vs_service_get’:
ofp_vs_ctl.c:344:2: warning: implicit declaration of function ‘container_of’ [-Wimplicit-function-declaration]
  list_for_each_entry(svc, ip_vs_svc_tab + hash, s_list) {
  ^
ofp_vs_ctl.c:344:2: warning: nested extern declaration of ‘container_of’ [-Wnested-externs]
In file included from ./include/ofp_vs.h:26:0,
                 from ofp_vs_ctl.c:33:
/opt/work/dpdk//x86_64-native-linuxapp-gcc/include/rte_common.h:55:16: error: expected expression before ‘__typeof__’
 #define typeof __typeof__
                ^
./include/kern_list.h:351:20: note: in definition of macro ‘list_entry’
  container_of(ptr, type, member)
                    ^
./include/kern_list.h:419:38: note: in expansion of macro ‘typeof’
  for (pos = list_entry((head)->next, typeof(*pos), member); \
                                      ^
ofp_vs_ctl.c:344:2: note: in expansion of macro ‘list_for_each_entry’
  list_for_each_entry(svc, ip_vs_svc_tab + hash, s_list) {

**Comment by jlijian3** [comment]
我刚刚更新了ofp_vs/Makefile.am，把-I/usr/loca/include/libnl3改掉了
在include/ofp_vs.h增加了#include <rte_common.h>看下能否解决这个编译问题

**Comment by alaleiwang** [comment]
还是不行，已经更新到最新代码
git log|head -n3
commit f6e78fa1eb881db4a526466287ae6cfdfc3e58d1
Author: lvsgate <lvsgate@163.com>
Date:   Fri Mar 17 17:23:38 2017 +0800

./bootstrap 
./configure --with-odp-lib=odp-dpdk --with-odp=/opt/work/ODP-DPDK/ --enable-shared=no --enable-sp=no --disable-mtrie
export RTE_TARGET=x86_64-native-linuxapp-gcc
export RTE_SDK=/opt/work/dpdk/

错误在于不能解析dpdk//x86_64-native-linuxapp-gcc/include/rte_common.h中的：
#define typeof __typeof__

和编译器环境有关系吗？

make[2]: Entering directory `/opt/work/ofp/example/ofp_vs'
  CC       ofp_vs-ofp_vs_ctl.o
ofp_vs_ctl.c: In function ‘__ip_vs_service_get’:
ofp_vs_ctl.c:344:2: warning: implicit declaration of function ‘container_of’ [-Wimplicit-function-declaration]
  list_for_each_entry(svc, ip_vs_svc_tab + hash, s_list) {
  ^
ofp_vs_ctl.c:344:2: warning: nested extern declaration of ‘container_of’ [-Wnested-externs]
In file included from ./include/ofp_vs.h:27:0,
                 from ofp_vs_ctl.c:33:
/opt/work/dpdk//x86_64-native-linuxapp-gcc/include/rte_common.h:55:16: error: expected expression before ‘__typeof__’
 #define typeof __typeof__
                ^
./include/kern_list.h:351:20: note: in definition of macro ‘list_entry’
  container_of(ptr, type, member)
                    ^
./include/kern_list.h:419:38: note: in expansion of macro ‘typeof’
  for (pos = list_entry((head)->next, typeof(*pos), member); \

**Comment by lvsgate** [comment]
我看了rte_common.h是这样的，你的#define typeof typeof是怎么回事？
54 #ifndef typeof
 55 #define typeof __typeof__
 56 #endif

**Comment by lvsgate** [comment]
我的版本是
gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC)

**Comment by alaleiwang** [comment]
gcc -v 2>&1|tail -n1 
gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) 

rpm -qa|grep glibc
glibc-2.17-106.el7_2.4.x86_64

看着差不多。。。

**Comment by alaleiwang** [comment]
dpdk编译是没有问题的，ofp关于ofp_vs 样例时引用的dpdk头文件代码解析问题，感觉和ofp的编译环境有关系

**Comment by alaleiwang** [comment]
编译过去了，是这个原因吗？

diff --git a/example/ofp_vs/include/kern_list.h b/example/ofp_vs/include/kern_list.h
index e618e99..4b8c971 100644
--- a/example/ofp_vs/include/kern_list.h
+++ b/example/ofp_vs/include/kern_list.h
@@ -336,10 +336,10 @@ static inline void list_splice_tail_init(struct list_head *list,
        }
 }
 
-/*
+
 #define container_of(ptr, type, member) \
   ((type *) ((char *) (ptr) - (unsigned long) (&((type *) 0)->member)))
-*/
+
 
 /**
  * list_entry - get the struct for this entry

**Comment by jlijian3** [comment]
这个我之所以注释掉，就是因为dpdk已经定义了container_of ，重定义了。我后续会加上#ifndef判断一下

**Comment by alaleiwang** [comment]
你有qq之类的联系方式吗

**Comment by jlijian3** [comment]
381478651

**Comment by lvsgate** [comment]
381478651
