### ISSUE TITLE
6.Run lvs-dpdk步骤报错main.c:495] ofp_vs_init() failed

### ISSUE THREAD

**Issue by w675881684** [lvsgate/lvs-dpdk#3]
测试环境：vmware RHEL7.2

follow below command:
export ODP_PLATFORM_PARAMS="-n 4"
./ofp_vs -i 0,1 -c 2 -o 0 -p 1 -f ofp.conf

I 1 0:693169024 ofp_uma.c:44] Creating pool 'tcptw', nitems=409 size=80 total=32720
I 1 0:693169024 ofp_uma.c:44] Creating pool 'syncache', nitems=30720 size=168 total=5160960
I 2 0:693169024 ofp_uma.c:44] Creating pool 'tcpreass', nitems=320 size=48 total=15360
I 2 0:693169024 ofp_uma.c:44] Creating pool 'sackhole', nitems=65536 size=40 total=2621440
I 3 0:693169024 ofp_init.c:195] Slow path threads on core 0
I 3 0:693169024 ofp_ifnet.c:143] Device '0' addr  00:0c:29:1a:76:13
I 3 0:693169024 ofp_ifnet.c:152] Device '0' MTU=1500
odp_thread.c:166:odp_thread_init_local():There is a thread already running on core 0
../linux-generic/odp_timer.c:683:timer_notify():
        1 ticks overrun on timer pool "TmrPool", timer resolution too high
I 9 0:693169024 main.c:365] if 0 rx_q 0 bind to cpu 0
I 9 0:693169024 ofp_ifnet.c:143] Device '1' addr  00:0c:29:1a:76:1d
I 9 0:693169024 ofp_ifnet.c:152] Device '1' MTU=1500
odp_thread.c:166:odp_thread_init_local():There is a thread already running on core 0
odp_thread.c:166:odp_thread_init_local():There is a thread already running on core 0
I 13 0:693169024 main.c:365] if 1 rx_q 0 bind to cpu 0
odp_thread.c:166:odp_thread_init_local():There is a thread already running on core 0
odp_thread.c:166:odp_thread_init_local():There is a thread already running on core 0
odp_thread.c:166:odp_thread_init_local():There is a thread already running on core 0
E 22 0:693169024 ofp_vs_ctl.c:3093] genl_osp_resolve return -12

E 22 0:693169024 ofp_vs_core.c:466] ofp_vs_ctl_init Unknown error -12 -12

E 22 0:693169024 main.c:495] ofp_vs_init() failed

End Worker
E 23 0:693169024 ofp_vs_sched.c:211] unregister_ip_vs_scheduler(): [rr] scheduler is not in the list. failed

E 23 0:693169024 ofp_vs_sched.c:211] unregister_ip_vs_scheduler(): [snat_sched] scheduler is not in the list. failed

Segmentation fault (core dumped)
[@linux /opt/ofp/example/ofp_vs]#

**Comment by w675881684** [comment]
export ODP_PLATFORM_PARAMS="-n 4 --huge-dir /mnt/huge"
./ofp_vs -i 0,1 -c 2 -o 0 -p 1 -f ofp.conf



I 2 0:1641335680 ofp_uma.c:44] Creating pool 'syncache', nitems=30720 size=168 total=5160960
I 2 0:1641335680 ofp_uma.c:44] Creating pool 'tcpreass', nitems=320 size=48 total=15360
I 2 0:1641335680 ofp_uma.c:44] Creating pool 'sackhole', nitems=65536 size=40 total=2621440
I 3 0:1641335680 ofp_init.c:195] Slow path threads on core 0
I 3 0:1641335680 ofp_ifnet.c:143] Device '0' addr  00:0c:29:1a:76:13
I 3 0:1641335680 ofp_ifnet.c:152] Device '0' MTU=1500
odp_thread.c:166:odp_thread_init_local():There is a thread already running on core 0
I 8 0:1641335680 main.c:365] if 0 rx_q 0 bind to cpu 0
I 8 0:1641335680 ofp_ifnet.c:143] Device '1' addr  00:0c:29:1a:76:1d
I 8 0:1641335680 ofp_ifnet.c:152] Device '1' MTU=1500
odp_thread.c:166:odp_thread_init_local():There is a thread already running on core 0
odp_thread.c:166:odp_thread_init_local():There is a thread already running on core 0
I 12 0:1641335680 main.c:365] if 1 rx_q 0 bind to cpu 0
../linux-generic/odp_timer.c:683:timer_notify():
        1 ticks overrun on timer pool "TmrPool", timer resolution too high
odp_thread.c:166:odp_thread_init_local():There is a thread already running on core 0
odp_thread.c:166:odp_thread_init_local():There is a thread already running on core 0
odp_thread.c:166:odp_thread_init_local():There is a thread already running on core 0
E 21 0:1641335680 ofp_vs_ctl.c:3093] genl_osp_resolve return -12

E 21 0:1641335680 ofp_vs_core.c:466] ofp_vs_ctl_init Unknown error -12 -12

E 21 0:1641335680 main.c:495] ofp_vs_init() failed

W 22 0:1511565056 ofp_udp_usrreq.c:575] badunlocked
odp_thread.c:166:odp_thread_init_local():There is a thread already running on core 0
I 0 0:1503172352 ofp_cli.c:1599] CLI server started on core 0

CONFIGURATION LINE: debug 0x0


CONFIGURATION LINE: loglevel set debug


CONFIGURATION LINE: ifconfig fp0 192.168.50.253/24

End Worker
E 23 0:1641335680 ofp_vs_sched.c:211] unregister_ip_vs_scheduler(): [rr] scheduler is not in the list. failed

E 23 0:1641335680 ofp_vs_sched.c:211] unregister_ip_vs_scheduler(): [snat_sched] scheduler is not in the list. failed

Segmentation fault (core dumped)

**Comment by lvsgate** [comment]
modprobe ip_vs
ipvsadm和keepalived使用netlink跟ofp_vs通信依赖ip_vs模块
