### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by yangxingwu** [lvsgate/lvs-dpdk#4]
classifier_main.c:(.text+0x45a): undefined reference to `odph_linux_pthread_create'
classifier_main.c:(.text+0x476): undefined reference to `odph_linux_pthread_join'
../../lib/.libs/libofp.a(ofp_cli.o): In function `ofp_start_cli_thread':
ofp_cli.c:(.text+0x3894): undefined reference to `odph_linux_pthread_create'
../../lib/.libs/libofp.a(ofp_cli.o): In function `ofp_stop_cli_thread':
ofp_cli.c:(.text+0x3a18): undefined reference to `odph_linux_pthread_join'
../../lib/.libs/libofp.a(ofp_init.o): In function `ofp_init_global':
ofp_init.c:(.text+0xaf2): undefined reference to `odph_linux_pthread_create'
../../lib/.libs/libofp.a(ofp_init.o): In function `ofp_term_global':
ofp_init.c:(.text+0xd6e): undefined reference to `odph_linux_pthread_join'
ofp_init.c:(.text+0xf0c): undefined reference to `odph_linux_pthread_join'
ofp_init.c:(.text+0xf26): undefined reference to `odph_linux_pthread_join'
../../lib/.libs/libofp.a(ofp_ifnet.o): In function `ofp_ifnet_create2':
ofp_ifnet.c:(.text+0x10f3): undefined reference to `odph_linux_pthread_create'
ofp_ifnet.c:(.text+0x1143): undefined reference to `odph_linux_pthread_create'

**Comment by yangxingwu** [comment]
完全按照步骤来的

**Comment by yangxingwu** [comment]
ubuntu 16.04

**Comment by yangxingwu** [comment]
解决了，编译odp-dpdk时，加上宏--enable-helper-linux

**Comment by lvsgate** [comment]
了解，configure odp-dpdk的时候增加--enable-helper-linux，上次合并ofp upstream的时候增加了这个依赖
./configure --with-platform=linux-dpdk --enable-helper-linux --with-sdk-install-path=<dpdk-dir>/x86_64-native-linuxapp-gcc --prefix=<INSTALL ODP-DPDK TO THIS DIR>

**Comment by yangxingwu** [comment]
嗯，多谢；期待交流，微信yxw-xyz

**Comment by lvsgate** [comment]
README下面有qq群号
