### ISSUE TITLE
Cannot allocate memory

### ISSUE THREAD

**Issue by Edward-L** [lvsgate/lvs-dpdk#5]
按照readme进行了安装，过程没有问题，第六步执行测试用例时大量报错
`
EAL: Detected 2 lcore(s)
EAL: Probing VFIO support...
EAL: PCI device 0000:02:01.0 on NUMA socket -1
EAL:   probe driver: 8086:100f net_e1000_em
EAL: PCI device 0000:02:01.0 on NUMA socket -1
EAL:   probe driver: 8086:100f net_e1000_em
EAL: PCI device 0000:02:05.0 on NUMA socket -1
EAL:   probe driver: 8086:100f net_e1000_em
 PKTIO: initialized loop interface.
No crypto devices available
odp_cpu_count : 2
Num worker threads: 1
first CPU:          1
cpu mask:           0x2
I 9 1:1164054272 ofp_uma.c:45] Creating pool 'udp_inpcb', nitems=1024 size=904 total=925696
I 9 1:1164054272 ofp_uma.c:45] Creating pool 'tcp_inpcb', nitems=2048 size=904 total=1851392
odp_pool.c:479:odp_pool_create():Cannot init DPDK mbuf pool: Cannot allocate memory
E 9 1:1164054272 ofp_uma.c:54] odp_pool_create failed
I 9 1:1164054272 ofp_uma.c:45] Creating pool 'tcpcb', nitems=2048 size=784 total=1605632
odp_pool.c:479:odp_pool_create():Cannot init DPDK mbuf pool: Cannot allocate memory
E 9 1:1164054272 ofp_uma.c:54] odp_pool_create failed
I 9 1:1164054272 ofp_uma.c:45] Creating pool 'tcptw', nitems=409 size=80 total=32720
I 9 1:1164054272 ofp_uma.c:45] Creating pool 'syncache', nitems=30720 size=168 total=5160960
odp_pool.c:479:odp_pool_create():Cannot init DPDK mbuf pool: Cannot allocate memory
E 9 1:1164054272 ofp_uma.c:54] odp_pool_create failed
I 9 1:1164054272 ofp_uma.c:45] Creating pool 'tcpreass', nitems=320 size=48 total=15360
I 9 1:1164054272 ofp_uma.c:45] Creating pool 'sackhole', nitems=65536 size=40 total=2621440
odp_pool.c:479:odp_pool_create():Cannot init DPDK mbuf pool: Cannot allocate memory
E 9 1:1164054272 ofp_uma.c:54] odp_pool_create failed
I 9 1:1164054272 ofp_init.c:245] Slow path threads on core 0
I 9 1:1164054272 ofp_ifnet.c:143] Device '0' addr  00:0c:29:7d:2e:ba
I 9 1:1164054272 ofp_ifnet.c:152] Device '0' MTU=1500
odp_thread.c:166:odp_thread_init_local():There is a thread already running on core 0
odp_thread.c:166:odp_thread_init_local():There is a thread already running on core 0
I 14 1:1164054272 main.c:369] if 0 rx_q 0 bind to cpu 1
odp_thread.c:166:odp_thread_init_local():There is a thread already running on core 0
../linux-generic/odp_packet_io.c:224:setup_pktio_entry():Unable to init any I/O type.
E 14 1:1164054272 ofp_ifnet.c:23] odp_pktio_open failed
E 14 1:1164054272 main.c:337] Failed to init interface 1
E 14 1:1164054272 main.c:477] create_ifnet_and_bind_queues failed
`

**Comment by lvsgate** [comment]
dpdk都设置好没，跑一下odp-dpdk或者dpdk的示例程序能不能跑起来
