### ISSUE TITLE
配置错误

### ISSUE THREAD

**Issue by Edward-L** [lvsgate/lvs-dpdk#6]
3. Fetch and compile ofp 配置configure时最后的cxxflags配置不进去，手动修改了configure的17981行
`  17981 AM_CPPFLAGS="$AM_CPPFLAGS $ODP_CFLAGS $ODPHELPER_CFLAGS $XYZ"`
在最后加上变量XYZ,然后改成
`./configure --with-odp-lib=odp-dpdk --with-odp=<ODP-DPDK INSTALLATION DIR> --enable-shared=no --enable-sp=yes --disable-mtrie XYZ=-I<ODP-DPDK INSTALLATION DIR>/include/odp/arch/x86_64-linux/`
才成功配置
第三步最后还差了个make install

**Comment by lvsgate** [comment]
./configure -h看一下，有CXXFLAGS, CPPFLAGS, CFLAGS，  试了CXXFLAGS, CPPFLAGS都有效

**Comment by Edward-L** [comment]
这是我configure的flag的结果
`cppflags:               
 am_cppflags:             -I/xxx/odp_dpdk/include -I/xxx/odp_dpdk/include`
没有
`/xxx/odp_dpdk/include/odp/arch/x86_64-linux/`这个路径

**Comment by yujianwei** [comment]
刚才碰到同样的问题，也是在 AM_CPPFLAGS 加了-I路径

**Comment by lvsgate** [comment]
试CPPFLAGS
